# Default values for IWO Kubernetes probe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#nameOverride: ""
#fullnameOverride: ""

# Replace the images with desired version
connectorImage:
# repository: intersight/pasadena
  repository: public.ecr.aws/d8i9k4x3/fso-lab-intersight-pasadena
  tag: 1.0.11-937
  pullPolicy: IfNotPresent

collectorImage:
# repository: intersight/kubeturbo
  repository: public.ecr.aws/d8i9k4x3/fso-lab-intersight-kubeturbo
  tag: 8.7.5.1
  pullPolicy: IfNotPresent

# The collector will spin off simple jobs to run at each node to collect its cpu frequency.
# The job is based on the busybox image.  Uncomment below to customize the repository.
# Note that currently neither the tag nor the pull policy is customizable.
#busyboxImage:
#  repository: busybox

# The credentials to log onto the image registry to pull images.  This applies to all the above 3 images.
#imagePullSecret: ""

# IWO server major.minor version
iwoServerVersion: 8.7

# Target config -
# - If no targetConfig is specified, a default targetName will be created from the apiserver URL in the kubeconfig.
# - A probe with type Kubernetes-<targetName> will be registered, as well as your cluster will be added as a target
#   with the name Kubernetes-<targetName>.
#
#targetName: Cluster_Name

# Specify custom iwo-cluster-reader or iwo-cluster-admin role instead of the default cluster-admin role
roleName: "cluster-admin"

replicaCount: 2

# You can define what nodes should stay high-available based on the node role
# Master nodes are by default populated by --set HANodeConfig.nodeRoles="\"foo\"\,\"bar\""
HANodeConfig:
  nodeRoles: "\"master\""

# You can define how daemon pods are identified. Use either or both
# Note if you do not enable daemonPodDetectors, the default is to identify all pods running as kind = daemonSet
# Any entry for daemonPodDetectors would overwrite default. Recommend you do not use this parameter.
#daemonPodDetectors:
#   daemonPodNamespaces1: kube-system
#   daemonPodNamespaces2: OpenShift
#   daemonPodNamePatterns: .*ignorePod.*

args:
  # logging level
  logginglevel: 2
  # If running on k8s 1.10.x or older, set https to false and change port 10255 for kubelet
  kubelethttps: true
  kubeletport: 10250
  # set to false if using IP for stitching
  stitchuuid: true
  # if Kubernetes version is older than 1.6, then add another arg for move/resize action
  pre16k8sVersion: false
  # change to false if you want to move pods which have volumes attached; the pod(s) will be down during move
  failVolumePodMoves: true

annotations:
  kubeturbo.io/controllable: "false"

resources: {}
